#     Q_DECLARE_FLAGS(KeyboardModifiers, KeyboardModifier)
#     Q_DECLARE_FLAGS(MouseButtons, MouseButton)
#     Q_DECLARE_FLAGS(Orientations, Orientation)
#     Q_DECLARE_FLAGS(Alignment, AlignmentFlag)
#     Q_DECLARE_FLAGS(WindowFlags, WindowType)
#     Q_DECLARE_FLAGS(WindowStates, WindowState)
#     Q_DECLARE_FLAGS(ImageConversionFlags, ImageConversionFlag)
#     Q_DECLARE_FLAGS(DockWidgetAreas, DockWidgetArea)
#     Q_DECLARE_FLAGS(ToolBarAreas, ToolBarArea)
#     Q_DECLARE_FLAGS(DropActions, DropAction)
#     Q_DECLARE_FLAGS(ItemFlags, ItemFlag)
#     Q_DECLARE_FLAGS(MatchFlags, MatchFlag)

header = 'QtCore/Qt'
Enum('Qt::KeyboardModifier', header)
Enum('Qt::GlobalColor', header)
Enum('Qt::Modifier', header)
Enum('Qt::MouseButton', header)
#Enum('Qt::ButtonState_enum', header)
Enum('Qt::Orientation', header)
Enum('Qt::FocusPolicy', header)
Enum('Qt::SortOrder', header)
Enum('Qt::AlignmentFlag', header)
Enum('Qt::TextFlag', header)
Enum('Qt::TextElideMode', header)
Enum('Qt::WindowType', header)
Enum('Qt::WindowState', header)
Enum('Qt::WidgetAttribute', header)
Enum('Qt::ImageConversionFlag', header)
Enum('Qt::BGMode', header)
#Enum('Qt::PaintUnit', header)
#Enum('Qt::GUIStyle', header)
Enum('Qt::Key', header)
Enum('Qt::ArrowType', header)
Enum('Qt::PenStyle', header)
Enum('Qt::PenCapStyle', header)
Enum('Qt::PenJoinStyle', header)
Enum('Qt::BrushStyle', header)
Enum('Qt::UIEffect', header)
Enum('Qt::CursorShape', header)
Enum('Qt::TextFormat', header)
#Enum('Qt::AspectRatioMode', header)
Enum('Qt::AnchorAttribute', header)
Enum('Qt::DockWidgetArea', header)
Enum('Qt::ToolBarArea', header)
#Enum('Qt::Dock', header)
Enum('Qt::DateFormat', header)
Enum('Qt::TimeSpec', header)
Enum('Qt::DayOfWeek', header)
Enum('Qt::ScrollBarPolicy', header)
#Enum('Qt::BackgroundMode', header)
Enum('Qt::CaseSensitivity', header)
Enum('Qt::Corner', header)
Enum('Qt::ConnectionType', header)
Enum('Qt::ShortcutContext', header)
Enum('Qt::FillRule', header)
Enum('Qt::ClipOperation', header)
Enum('Qt::TransformationMode', header)
Enum('Qt::FocusReason', header)
Enum('Qt::ContextMenuPolicy', header)
Enum('Qt::InputMethodQuery', header)
Enum('Qt::ToolButtonStyle', header)
Enum('Qt::LayoutDirection', header)
Enum('Qt::DropAction', header)
Enum('Qt::CheckState', header)
Enum('Qt::ItemDataRole', header)
Enum('Qt::ItemFlag', header)
Enum('Qt::MatchFlag', header)
#Enum('Qt::PaintDeviceFlags', header)
#Enum('Qt::RelayoutType', header)
#Enum('MacintoshVersion', header)
#Enum('WindowsVersion', header)

